# GroupKFoldとかfor ind in folds[:,1]: についての確認    

参考  
https://runebook.dev/ja/docs/scikit_learn/modules/generated/sklearn.model_selection.groupkfold

In [1]:
import numpy as np
from sklearn.model_selection import GroupKFold
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8],[9,10],[11,12]])
#y = np.array([1, 2, 3, 4])
groups = np.array([0, 0, 2, 2,4,4])
group_kfold = GroupKFold(n_splits=3)


for train_index, test_index in group_kfold.split(X, groups=groups):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    #y_train, y_test = y[train_index], y[test_index]
    print(X_train, X_test)

TRAIN: [0 1 2 3] TEST: [4 5]
[[1 2]
 [3 4]
 [5 6]
 [7 8]] [[ 9 10]
 [11 12]]
TRAIN: [0 1 4 5] TEST: [2 3]
[[ 1  2]
 [ 3  4]
 [ 9 10]
 [11 12]] [[5 6]
 [7 8]]
TRAIN: [2 3 4 5] TEST: [0 1]
[[ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]] [[1 2]
 [3 4]]


In [2]:
folds = np.array(list( group_kfold.split(X, groups=groups) ))
print(folds)

[[array([0, 1, 2, 3]) array([4, 5])]
 [array([0, 1, 4, 5]) array([2, 3])]
 [array([2, 3, 4, 5]) array([0, 1])]]


/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [3]:
print(folds[0])

[array([0, 1, 2, 3]) array([4, 5])]


In [4]:
print(folds[1])

[array([0, 1, 4, 5]) array([2, 3])]


In [5]:
print(folds[:,1])

[array([4, 5]) array([2, 3]) array([0, 1])]


In [6]:
for ind in folds[:,1]:
    print(ind)

[4 5]
[2 3]
[0 1]


In [7]:
gt_indices = []
for ind in folds[:,1]: gt_indices.extend(ind)
print(gt_indices)

[4, 5, 2, 3, 0, 1]


# setとdifferenceの確認

In [8]:
s = set(range(0,10))
print(s)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}


In [9]:
print(s.difference(set(range(3,5))))

{0, 1, 2, 5, 6, 7, 8, 9}


In [10]:
print(list(s.difference(set(range(3,5)))))

[0, 1, 2, 5, 6, 7, 8, 9]


In [11]:
out = np.array(np.array_split(list(s.difference(set(range(3,5)))),3))
print(out)

[array([0, 1, 2]) array([5, 6, 7]) array([8, 9])]


/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.
